import crypto from 'crypto';

// 256-bit encryption secret derived from environment or military-grade default
const ENCRYPTION_SECRET = process.env.ENCRYPTION_SECRET || 'isdvp_mospi_gov_secure_aes256_key_2026_x89f!';
const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 16;
const SALT_LENGTH = 32;
const KEY_LENGTH = 32;

/**
 * Derive a 32-byte key using PBKDF2 with 100,000 iterations
 */
function deriveKey(secret: string, salt: Buffer): Buffer {
  return crypto.pbkdf2Sync(secret, salt, 100000, KEY_LENGTH, 'sha256');
}

/**
 * Encrypt a text or JSON string using AES-256-GCM with authentication tag
 */
export function encryptData(plainText: string): { cipherText: string; iv: string; tag: string; salt: string } {
  const iv = crypto.randomBytes(IV_LENGTH);
  const salt = crypto.randomBytes(SALT_LENGTH);
  const key = deriveKey(ENCRYPTION_SECRET, salt);

  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  let encrypted = cipher.update(plainText, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  const tag = cipher.getAuthTag();

  return {
    cipherText: encrypted,
    iv: iv.toString('hex'),
    tag: tag.toString('hex'),
    salt: salt.toString('hex'),
  };
}

/**
 * Decrypt a cipher package generated by encryptData
 */
export function decryptData(cipherText: string, ivHex: string, tagHex: string, saltHex: string): string {
  const iv = Buffer.from(ivHex, 'hex');
  const tag = Buffer.from(tagHex, 'hex');
  const salt = Buffer.from(saltHex, 'hex');
  const key = deriveKey(ENCRYPTION_SECRET, salt);

  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(tag);

  let decrypted = decipher.update(cipherText, 'hex', 'utf8');
  decrypted += decipher.final('utf8');

  return decrypted;
}

/**
 * Encrypt any JS object into a compact, self-contained AES-256-GCM envelope
 */
export function encryptPayload(data: any): string {
  const text = typeof data === 'string' ? data : JSON.stringify(data);
  const { cipherText, iv, tag, salt } = encryptData(text);
  return `ENC:v1:${salt}:${iv}:${tag}:${cipherText}`;
}

/**
 * Decrypt a self-contained AES-256-GCM envelope
 */
export function decryptPayload<T = any>(envelope: string): T {
  if (!envelope.startsWith('ENC:v1:')) {
    throw new Error('Invalid encryption envelope prefix');
  }
  const parts = envelope.split(':');
  if (parts.length !== 6) {
    throw new Error('Malformed encryption envelope format');
  }
  const [, , salt, iv, tag, cipherText] = parts;
  const decrypted = decryptData(cipherText, iv, tag, salt);
  try {
    return JSON.parse(decrypted) as T;
  } catch {
    return decrypted as unknown as T;
  }
}

/**
 * Helper to generate a SHA-256 checksum for audit, file & backup integrity verification
 */
export function generateChecksum(data: string | Buffer): string {
  return crypto.createHash('sha256').update(data).digest('hex');
}

/**
 * Privacy preservation & PII Data Masking helper
 */
export function maskPII(value: string, type: 'email' | 'id' | 'name' | 'phone'): string {
  if (!value) return '';
  switch (type) {
    case 'email': {
      const parts = value.split('@');
      if (parts.length < 2) return '***@***.***';
      const [name, domain] = parts;
      const maskedName = name.length > 2 ? `${name[0]}${'*'.repeat(name.length - 2)}${name[name.length - 1]}` : `${name[0]}*`;
      return `${maskedName}@${domain}`;
    }
    case 'id': {
      if (value.length <= 4) return '****';
      return `${value.slice(0, 2)}${'*'.repeat(Math.max(2, value.length - 4))}${value.slice(-2)}`;
    }
    case 'phone': {
      if (value.length < 6) return '******';
      return `+91 ${value.slice(0, 2)}******${value.slice(-2)}`;
    }
    case 'name': {
      const parts = value.split(' ');
      return parts.map(p => (p.length > 1 ? `${p[0]}${'.'.repeat(p.length - 1)}` : p)).join(' ');
    }
    default:
      return '********';
  }
}

