import { jsPDF } from 'jspdf';

export function generateAuditPdfReport(
  reportTitle: string,
  batchInfo: { surveyName: string; quarter: string; recordCount: number },
  flags: any[],
  generatedByName: string
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header Banner
  doc.setFillColor(18, 22, 59); // Dark Navy #12163B
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('GOVERNMENT OF INDIA · MoSPI / NSO', 14, 18);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(20, 184, 166); // Teal #14B8A6
  doc.text('Intelligent Survey Data Validation Platform (ISDVP) · Data Quality Audit', 14, 28);

  // Document Metadata Section
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(reportTitle, 14, 52);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Survey: ${batchInfo.surveyName} | Round/Quarter: ${batchInfo.quarter} | Total Batch Records: ${batchInfo.recordCount}`, 14, 60);
  doc.text(`Generated By: ${generatedByName} | Audit Timestamp: ${new Date().toLocaleString()}`, 14, 66);

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 72, pageWidth - 14, 72);

  // Summary Metrics Box
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 78, pageWidth - 28, 28, 3, 3, 'F');

  const highCount = flags.filter((f) => f.severity === 'high').length;
  const mediumCount = flags.filter((f) => f.severity === 'medium').length;
  const openCount = flags.filter((f) => f.status === 'open').length;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(18, 22, 59);
  doc.text('Executive Summary of Flagged Anomalies:', 20, 88);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`• Total Anomalies Analyzed: ${flags.length}`, 20, 96);
  doc.text(`• High Severity Alerts: ${highCount}`, 85, 96);
  doc.text(`• Actionable Open Flags: ${openCount}`, 145, 96);

  // Table Section Header
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(18, 22, 59);
  doc.text('Sample Detailed Flag Audit Roster (Top Entries)', 14, 118);

  // Table Headers
  let y = 126;
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y - 5, pageWidth - 28, 8, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);

  doc.text('RECORD / FILE ID', 16, y);
  doc.text('METHOD', 65, y);
  doc.text('SCORE', 95, y);
  doc.text('SEVERITY', 115, y);
  doc.text('STATUS', 140, y);
  doc.text('STATE / DIST', 165, y);

  y += 6;

  // Table Rows (Top 12 entries to fit cleanly)
  const displayFlags = flags.slice(0, 14);
  doc.setFont('helvetica', 'normal');

  displayFlags.forEach((flag, index) => {
    if (index % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(14, y - 4, pageWidth - 28, 7, 'F');
    }

    doc.setTextColor(30, 41, 59);
    doc.text(flag.record?.fileId || `REC_${flag.id.slice(0, 8)}`, 16, y);
    doc.text((flag.detectionMethod || 'ml').toUpperCase(), 65, y);
    doc.text(`${Math.round(flag.anomalyScore || 80)}%`, 95, y);
    
    // Severity color
    if (flag.severity === 'high') {
      doc.setTextColor(220, 38, 38);
    } else if (flag.severity === 'medium') {
      doc.setTextColor(217, 119, 6);
    } else {
      doc.setTextColor(13, 148, 136);
    }
    doc.text((flag.severity || 'medium').toUpperCase(), 115, y);

    doc.setTextColor(71, 85, 105);
    doc.text(flag.status || 'open', 140, y);
    doc.text(`ST:${flag.record?.stateCode || '07'} / DT:${flag.record?.districtCode || '01'}`, 165, y);

    y += 7;
  });

  // Footer Note
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Official Government of India MoSPI/NSO Survey Validation Record. Generated automatically by ISDVP.', 14, 285);

  doc.save(`${reportTitle.toLowerCase().replace(/\s+/g, '_')}.pdf`);
}
